# activate this profile when running RedisKafkaElasticSearch app locally (via IntelliJ)
spring:
  datasource:
    url: "jdbc:sqlite:db/db.sqlite"
    username: "sa"
    password: "sa"
    driver-class-name: "org.sqlite.JDBC"
  data:
    redis:
      host: "localhost"
      port: "6379"
  elasticsearch:
    uris: "localhost:9200"
  kafka:
    bootstrap-servers: "localhost:29092"