# activate this profile when running RedisKafkaElasticSearch app in docker container
spring:
  datasource:
    url: "jdbc:sqlite:db.sqlite"
    username: "sa"
    password: "sa"
    driver-class-name: "org.sqlite.JDBC"
  data:
    redis:
      host: "bitnami_redis"
      port: "6379"
  elasticsearch:
    uris: "elasticsearch:9200"
  kafka:
    bootstrap-servers: "kafka:29092"
