version: "3"

services:
  elasticsearch:
    image: "elasticsearch:8.8.0"
    container_name: "elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=elasticsearch

  kibana:
    image: "kibana:8.8.0"
    container_name: "kibana"
    ports:
      - "5601:5601"