version: "3"

services:
  redisinsight:
    image: "redis/redisinsight:2.52"
    container_name: "redisinsight"
    ports:
      - "5540:5540"

    networks:
      - rkes-nw


  kibana:
    image: "kibana:8.8.0"
    container_name: "kibana"
    ports:
      - "5601:5601"
    networks:
      - rkes-nw


  kafdrop:
    image: "obsidiandynamics/kafdrop:latest"
    container_name: "kafdrop"
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    networks:
      - rkes-nw


networks:
  rkes-nw:
    external: true